jobs:
  - job: ubuntu18_gcc10
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: templates/install-gcc.yml
        parameters:
          version: '10'
      - script: |
          which g++ && g++ --version
          cmake --version
        displayName: 'Check environment'
      - template: templates/install-boost.yml
      - script: |
          sudo apt-get install ninja-build
        displayName: 'Install Ninja'
      - script: |
          export LDFLAGS="-fuse-ld=gold"
          cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH=_deps/boost_1_67_0 -DCMAKE_BUILD_TYPE=Release -DKL_ENABLE_YAML=OFF
          cmake --build build
        displayName: 'Build kl'
      - script: |
          cd build && ctest -VV --output-on-failure
        displayName: 'Run CTest'

  - job: windows_vc2019
    pool:
      vmImage: 'windows-2019'
    variables:
      CL: /MP
    strategy:
      matrix:
        Win32:
          Architecture: Win32
        Win64:
          Architecture: x64
    steps:
      - script: |
          cmake --version
        displayName: 'Check environment'
      - template: templates/install-boost.yml
      - script: |
          cmake.exe -S . -B build -DCMAKE_PREFIX_PATH=_deps/boost_1_67_0 -G "Visual Studio 16 2019" -A $(Architecture) -DKL_ENABLE_YAML=OFF
          cmake.exe --build build --config Release
        displayName: 'Build kl'
      - script: |
          cd build && ctest --build-config Release -VV --output-on-failure
        displayName: 'Run CTest'
